DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TRAIN_U:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 1e-2
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_MIN_LR: 1e-4

TRAIN:
  PRINT_FREQ: 500

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"


